export const questions = [
  {
    id: 1,
    question: 'How would you design a globally distributed URL shortening service?',
    correct: 'Use consistent hashing, globally unique IDs, multi-region replication, and eventual consistency',
    skill: 'distributed-systems',
  },
  {
    id: 2,
    question: 'How do you prevent write hotspots in a distributed database?',
    correct: 'Use sharding with well-distributed keys and avoid sequential IDs',
    skill: 'databases',
  },
  {
    id: 3,
    question: 'What trade-offs exist between strong consistency and availability?',
    correct: 'Strong consistency reduces availability during network partitions',
    skill: 'distributed-systems',
  },
  {
    id: 4,
    question: 'How would you design an API rate limiter for millions of users?',
    correct: 'Use a distributed token bucket or leaky bucket with Redis',
    skill: 'api',
  },
  {
    id: 5,
    question: 'How would you handle schema changes without downtime?',
    correct: 'Use backward-compatible changes, feature flags, and phased deployments',
    skill: 'databases',
  },
  {
    id: 6,
    question: 'How do you ensure exactly-once message processing?',
    correct: 'Use idempotent consumers and transactional outbox patterns',
    skill: 'backend',
  },
  {
    id: 7,
    question: 'What is the main bottleneck in a high-write distributed system?',
    correct: 'Network latency and coordination overhead',
    skill: 'performance',
  },
  {
    id: 8,
    question: 'How would you design a system to handle flash traffic spikes?',
    correct: 'Auto-scaling, load balancing, caching, and graceful degradation',
    skill: 'architecture',
  },
  {
    id: 9,
    question: 'What is the impact of network partitions on distributed systems?',
    correct: 'They force a trade-off between consistency and availability',
    skill: 'distributed-systems',
  },
  {
    id: 10,
    question: 'How do you design a highly available authentication system?',
    correct: 'Stateless tokens, replicated user stores, and multi-region failover',
    skill: 'security',
  },
  {
    id: 11,
    question: 'What causes cascading failures and how do you prevent them?',
    correct: 'Tight coupling and retries without limits; prevent with circuit breakers and timeouts',
    skill: 'reliability',
  },
  {
    id: 12,
    question: 'How would you design a real-time notification system?',
    correct: 'Use message queues, WebSockets, and horizontal scaling',
    skill: 'backend',
  },
  {
    id: 13,
    question: 'What is the difference between synchronous replication and asynchronous replication?',
    correct: 'Synchronous waits for replicas to confirm, asynchronous does not',
    skill: 'databases',
  },
  {
    id: 14,
    question: 'How do you decide between SQL and NoSQL for a new system?',
    correct: 'Based on consistency needs, data relationships, and access patterns',
    skill: 'databases',
  },
  {
    id: 15,
    question: 'How would you design a distributed locking mechanism?',
    correct: 'Use Redis with expiration or consensus-based systems like etcd',
    skill: 'distributed-systems',
  },
  {
    id: 16,
    question: 'What are the risks of distributed transactions?',
    correct: 'High latency, partial failures, and complexity',
    skill: 'distributed-systems',
  },
  {
    id: 17,
    question: 'How do you handle data migrations at scale?',
    correct: 'Use backfills, dual writes, and background migration jobs',
    skill: 'databases',
  },
  {
    id: 18,
    question: 'How would you design a leaderboard system with millions of users?',
    correct: 'Use sorted sets, caching, and periodic batch updates',
    skill: 'performance',
  },
  {
    id: 19,
    question: 'What is the purpose of quorum reads and writes?',
    correct: 'To balance consistency and availability in distributed systems',
    skill: 'distributed-systems',
  },
  {
    id: 20,
    question: 'How do you detect and recover from partial system failures?',
    correct: 'Health checks, retries with backoff, and automated failover',
    skill: 'reliability',
  },
  {
    id: 21,
    question: 'How would you design a multi-tenant SaaS backend?',
    correct: 'Tenant isolation, scoped access control, and resource quotas',
    skill: 'architecture',
  },
  {
    id: 22,
    question: 'What is the biggest challenge in horizontal scaling databases?',
    correct: 'Maintaining data consistency across shards',
    skill: 'databases',
  },
  {
    id: 23,
    question: 'How do you manage secrets in production systems?',
    correct: 'Use secure secret managers and rotate credentials regularly',
    skill: 'security',
  },
  {
    id: 24,
    question: 'How would you design a system to guarantee data durability?',
    correct: 'Write-ahead logging, replication, and backups',
    skill: 'databases',
  },
  {
    id: 25,
    question: 'What are the dangers of over-caching?',
    correct: 'Stale data, cache invalidation complexity, and memory pressure',
    skill: 'performance',
  },
  {
    id: 26,
    question: 'How would you design a search system at scale?',
    correct: 'Use inverted indexes, sharding, and distributed search engines',
    skill: 'backend',
  },
  {
    id: 27,
    question: 'What is the trade-off between latency and throughput?',
    correct: 'Optimizing for one often degrades the other',
    skill: 'performance',
  },
  {
    id: 28,
    question: 'How do you design APIs for backward compatibility?',
    correct: 'Versioning, optional fields, and additive changes',
    skill: 'api',
  },
  {
    id: 29,
    question: 'What is eventual idempotency?',
    correct: 'Ensuring repeated operations eventually converge to the same result',
    skill: 'backend',
  },
  {
    id: 30,
    question: 'How do you ensure observability in large systems?',
    correct: 'Logging, metrics, tracing, and alerting',
    skill: 'observability',
  },
  {
    id: 31,
    question: 'How would you design a payments processing system?',
    correct: 'Idempotency keys, strong consistency, and audit logs',
    skill: 'security',
  },
  {
    id: 32,
    question: 'What is the hardest problem in distributed caching?',
    correct: 'Cache invalidation',
    skill: 'performance',
  },
  {
    id: 33,
    question: 'How do you handle duplicate events in event-driven systems?',
    correct: 'Use idempotent handlers and deduplication keys',
    skill: 'backend',
  },
  {
    id: 34,
    question: 'What is a split-brain scenario?',
    correct: 'When multiple nodes think they are the primary leader',
    skill: 'distributed-systems',
  },
  {
    id: 35,
    question: 'How do you avoid split-brain?',
    correct: 'Leader election using quorum-based consensus',
    skill: 'distributed-systems',
  },
  {
    id: 36,
    question: 'How would you design a system for GDPR data deletion?',
    correct: 'Data lineage tracking and cascading deletion workflows',
    skill: 'security',
  },
  {
    id: 37,
    question: 'What are the risks of shared databases across microservices?',
    correct: 'Tight coupling and limited independent scalability',
    skill: 'architecture',
  },
  {
    id: 38,
    question: 'How do you measure system reliability?',
    correct: 'Using SLIs, SLOs, and error budgets',
    skill: 'reliability',
  },
  {
    id: 39,
    question: 'How do you design systems for failure instead of success?',
    correct: 'Assume failures will happen and build redundancy',
    skill: 'architecture',
  },
  {
    id: 40,
    question: 'What distinguishes a senior backend engineer from a junior?',
    correct: 'Ability to reason about trade-offs, scalability, and failure modes',
    skill: 'backend',
  },
]
