export const questions = [
  { id: 1, question: 'How would you design a globally distributed URL shortening service?', correct: 'Use consistent hashing, globally unique IDs, multi-region replication, and eventual consistency', skill: 'System Design' },
  { id: 2, question: 'How do you prevent write hotspots in a distributed database?', correct: 'Use sharding with well-distributed keys and avoid sequential IDs', skill: 'Database Design' },
  { id: 3, question: 'What trade-offs exist between strong consistency and availability?', correct: 'Strong consistency reduces availability during network partitions', skill: 'Distributed Systems' },
  { id: 4, question: 'How would you design an API rate limiter for millions of users?', correct: 'Use a distributed token bucket or leaky bucket with Redis', skill: 'System Design' },
  { id: 5, question: 'How would you handle schema changes without downtime?', correct: 'Use backward-compatible changes, feature flags, and phased deployments', skill: 'Database Design' },
  { id: 6, question: 'How do you ensure exactly-once message processing?', correct: 'Use idempotent consumers and transactional outbox patterns', skill: 'Messaging Systems' },
  { id: 7, question: 'What is the main bottleneck in a high-write distributed system?', correct: 'Network latency and coordination overhead', skill: 'Distributed Systems' },
  { id: 8, question: 'How would you design a system to handle flash traffic spikes?', correct: 'Auto-scaling, load balancing, caching, and graceful degradation', skill: 'System Design' },
  { id: 9, question: 'What is the impact of network partitions on distributed systems?', correct: 'They force a trade-off between consistency and availability', skill: 'Distributed Systems' },
  { id: 10, question: 'How do you design a highly available authentication system?', correct: 'Stateless tokens, replicated user stores, and multi-region failover', skill: 'Authentication' },
  { id: 11, question: 'What causes cascading failures and how do you prevent them?', correct: 'Tight coupling and retries without limits; prevent with circuit breakers and timeouts', skill: 'System Design' },
  { id: 12, question: 'How would you design a real-time notification system?', correct: 'Use message queues, WebSockets, and horizontal scaling', skill: 'Messaging Systems' },
  { id: 13, question: 'What is the difference between synchronous replication and asynchronous replication?', correct: 'Synchronous waits for replicas to confirm, asynchronous does not', skill: 'Database Design' },
  { id: 14, question: 'How do you decide between SQL and NoSQL for a new system?', correct: 'Based on consistency needs, data relationships, and access patterns', skill: 'Database Design' },
  { id: 15, question: 'How would you design a distributed locking mechanism?', correct: 'Use Redis with expiration or consensus-based systems like etcd', skill: 'Distributed Systems' },
  { id: 16, question: 'What are the risks of distributed transactions?', correct: 'High latency, partial failures, and complexity', skill: 'Database Design' },
  { id: 17, question: 'How do you handle data migrations at scale?', correct: 'Use backfills, dual writes, and background migration jobs', skill: 'Database Design' },
  { id: 18, question: 'How would you design a leaderboard system with millions of users?', correct: 'Use sorted sets, caching, and periodic batch updates', skill: 'System Design' },
  { id: 19, question: 'What is the purpose of quorum reads and writes?', correct: 'To balance consistency and availability in distributed systems', skill: 'Distributed Systems' },
  { id: 20, question: 'How do you detect and recover from partial system failures?', correct: 'Health checks, retries with backoff, and automated failover', skill: 'System Design' },
  { id: 21, question: 'How would you design a multi-tenant SaaS backend?', correct: 'Tenant isolation, scoped access control, and resource quotas', skill: 'System Design' },
  { id: 22, question: 'What is the biggest challenge in horizontal scaling databases?', correct: 'Maintaining data consistency across shards', skill: 'Database Design' },
  { id: 23, question: 'How do you manage secrets in production systems?', correct: 'Use secure secret managers and rotate credentials regularly', skill: 'Security' },
  { id: 24, question: 'How would you design a system to guarantee data durability?', correct: 'Write-ahead logging, replication, and backups', skill: 'Database Design' },
  { id: 25, question: 'What are the dangers of over-caching?', correct: 'Stale data, cache invalidation complexity, and memory pressure', skill: 'Caching' },
  { id: 26, question: 'How would you design a search system at scale?', correct: 'Use inverted indexes, sharding, and distributed search engines', skill: 'Search Systems' },
  { id: 27, question: 'What is the trade-off between latency and throughput?', correct: 'Optimizing for one often degrades the other', skill: 'Performance' },
  { id: 28, question: 'How do you design APIs for backward compatibility?', correct: 'Versioning, optional fields, and additive changes', skill: 'API Design' },
  { id: 29, question: 'What is eventual idempotency?', correct: 'Ensuring repeated operations eventually converge to the same result', skill: 'Messaging Systems' },
  { id: 30, question: 'How do you ensure observability in large systems?', correct: 'Logging, metrics, tracing, and alerting', skill: 'Monitoring' },
  { id: 31, question: 'How would you design a payments processing system?', correct: 'Idempotency keys, strong consistency, and audit logs', skill: 'Payments' },
  { id: 32, question: 'What is the hardest problem in distributed caching?', correct: 'Cache invalidation', skill: 'Caching' },
  { id: 33, question: 'How do you handle duplicate events in event-driven systems?', correct: 'Use idempotent handlers and deduplication keys', skill: 'Messaging Systems' },
  { id: 34, question: 'What is a split-brain scenario?', correct: 'When multiple nodes think they are the primary leader', skill: 'Distributed Systems' },
  { id: 35, question: 'How do you avoid split-brain?', correct: 'Leader election using quorum-based consensus', skill: 'Distributed Systems' },
  { id: 36, question: 'How would you design a system for GDPR data deletion?', correct: 'Data lineage tracking and cascading deletion workflows', skill: 'Compliance' },
  { id: 37, question: 'What are the risks of shared databases across microservices?', correct: 'Tight coupling and limited independent scalability', skill: 'Distributed Systems' },
  { id: 38, question: 'How do you measure system reliability?', correct: 'Using SLIs, SLOs, and error budgets', skill: 'Monitoring' },
  { id: 39, question: 'How do you design systems for failure instead of success?', correct: 'Assume failures will happen and build redundancy', skill: 'System Design' },
  { id: 40, question: 'What distinguishes a senior backend engineer from a junior?', correct: 'Ability to reason about trade-offs, scalability, and failure modes', skill: 'System Design' },
]
